name: Packaging
run-name: Build ${{ inputs.minimal && 'minimal set of' || 'all' }} packages (version=${{ inputs.set-version != '' && inputs.set-version || 'dev' }}, tests=${{ inputs.testsuite }}, ref=${{ inputs.git-ref }}, duckdb ref=${{ inputs.duckdb-git-ref }})
on:
  workflow_dispatch:
    inputs:
      minimal:
        type: boolean
        description: Build a minimal set of wheels to do a sanity check
        default: false
      testsuite:
        type: choice
        description: Testsuite to run (none, fast, all)
        required: true
        default: all
        options:
          - none
          - fast
          - all
      git-ref:
        type: string
        description: Git ref of the DuckDB python package
        required: false
      duckdb-git-ref:
        type: string
        description: Git ref of DuckDB
        required: true
        default: refs/heads/main
      set-version:
        type: string
        description: Force version (vX.Y.Z-((rc|post)N))
        required: false
  workflow_call:
    inputs:
      minimal:
        type: boolean
        description: Build a minimal set of wheels to do a sanity check
        default: false
      testsuite:
        type: string
        description: Testsuite to run (none, fast, all)
        required: true
        default: all
      git-ref:
        type: string
        description: Git ref of the DuckDB python package
        required: false
      duckdb-git-ref:
        type: string
        description: Git ref of DuckDB
        required: false
      set-version:
        description: Force version (vX.Y.Z-((rc|post)N))
        required: false
        type: string

concurrency:
  group: packaging-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build_sdist:
    name: Build an sdist and determine versions
    uses: ./.github/workflows/packaging_sdist.yml
    with:
      testsuite: all
      git-ref: ${{ github.ref }}
      duckdb-git-ref: ${{ inputs.duckdb-sha }}
      set-version: ${{ inputs.stable-version }}

  build_wheels:
    name: Build and test releases
    uses: ./.github/workflows/packaging_wheels.yml
    with:
      minimal: false
      testsuite: all
      git-ref: ${{ github.ref }}
      duckdb-git-ref: ${{ inputs.duckdb-sha }}
      set-version: ${{ inputs.stable-version }}
